In [ ]:
import numpy as np
import pandas as pd

%cd /content/drive/MyDrive/GSoC 21 CERN

/content/drive/MyDrive/GSoC 21 CERN


### Load dataset from Google Drive

In [ ]:
df = pd.DataFrame([line.strip().split(';') for line in open('monojet_Zp2000.0_DM_50.0_chan3.csv', 'r')])
df.head()

0                         1            2   ...    15    16    17
0  354  monojet_Zp2000.0_DM_50.0  2.44336e-05  ...  None  None  None
1  354  monojet_Zp2000.0_DM_50.0  2.44336e-05  ...  None  None  None
2  354  monojet_Zp2000.0_DM_50.0  2.44336e-05  ...  None  None  None
3  354  monojet_Zp2000.0_DM_50.0  2.44336e-05  ...  None  None  None
4  354  monojet_Zp2000.0_DM_50.0  2.44336e-05  ...  None  None  None

[5 rows x 18 columns]

### Keep only first 5 columns from the dataset

In [ ]:
df=df.values
df=df[:,5:].reshape(-1)
print(df[:5])

['b,947383,824498,-0.523103,1.64421' 'j,258722,243675,0.328962,2.25014'
 'j,520092,108590,-2.2473,-1.85679' 'j,383024,88405.6,2.14516,-1.95635'
 'j,39507.6,35365.1,0.47046,-1.16445']


### Remove rows containing null values

In [ ]:
df=df[df!=None]
df=df[df!='']
print(df[:5])

['b,947383,824498,-0.523103,1.64421' 'j,258722,243675,0.328962,2.25014'
 'j,520092,108590,-2.2473,-1.85679' 'j,383024,88405.6,2.14516,-1.95635'
 'j,39507.6,35365.1,0.47046,-1.16445']


In [ ]:
df = np.array([d.split(',') for d in df])
print(df[:5])
print(np.shape(df))

[['b' '947383' '824498' '-0.523103' '1.64421']
 ['j' '258722' '243675' '0.328962' '2.25014']
 ['j' '520092' '108590' '-2.2473' '-1.85679']
 ['j' '383024' '88405.6' '2.14516' '-1.95635']
 ['j' '39507.6' '35365.1' '0.47046' '-1.16445']]
(23473, 5)


### Keep only observations with obj<sub>id</sub> = j

And remove the first column containing obj<sub>id</sub>

In [ ]:
df=df[df[:,0]=='j']
print(df[:5])
print(np.shape(df))

[['j' '258722' '243675' '0.328962' '2.25014']
 ['j' '520092' '108590' '-2.2473' '-1.85679']
 ['j' '383024' '88405.6' '2.14516' '-1.95635']
 ['j' '39507.6' '35365.1' '0.47046' '-1.16445']
 ['j' '225430' '26878.2' '-2.81608' '-2.25938']]
(22661, 5)


In [ ]:
df=df[:,1:]
print(df[:5])
print(np.shape(df))

[['258722' '243675' '0.328962' '2.25014']
 ['520092' '108590' '-2.2473' '-1.85679']
 ['383024' '88405.6' '2.14516' '-1.95635']
 ['39507.6' '35365.1' '0.47046' '-1.16445']
 ['225430' '26878.2' '-2.81608' '-2.25938']]
(22661, 4)


In [ ]:
df=df.astype(float)
print(df[:5])
print(np.shape(df))

[[ 2.58722e+05  2.43675e+05  3.28962e-01  2.25014e+00]
 [ 5.20092e+05  1.08590e+05 -2.24730e+00 -1.85679e+00]
 [ 3.83024e+05  8.84056e+04  2.14516e+00 -1.95635e+00]
 [ 3.95076e+04  3.53651e+04  4.70460e-01 -1.16445e+00]
 [ 2.25430e+05  2.68782e+04 -2.81608e+00 -2.25938e+00]]
(22661, 4)


In [ ]:
df = pd.DataFrame(df, columns=['E', 'pt', 'eta', 'phi'])
df.head()

E        pt       eta      phi
0  258722.0  243675.0  0.328962  2.25014
1  520092.0  108590.0 -2.247300 -1.85679
2  383024.0   88405.6  2.145160 -1.95635
3   39507.6   35365.1  0.470460 -1.16445
4  225430.0   26878.2 -2.816080 -2.25938

### Normalise the variables


 based on the values shared in [dataset.pdf](https://zenodo.org/record/3961917/files/dataset.pdf)

In [ ]:
df['eta'] = df['eta'] / 5
df['phi'] = df['phi'] / 3
df['E'] = np.log10(df['E'])
df['pt'] = np.log10(df['pt'])

df.head()

E        pt       eta       phi
0  5.412833  5.386811  0.065792  0.750047
1  5.716080  5.035790 -0.449460 -0.618930
2  5.583226  4.946480  0.429032 -0.652117
3  4.596681  4.548575  0.094092 -0.388150
4  5.353012  4.429400 -0.563216 -0.753127

### Store the processed dataset dataframe as a pickled dump to be used in the notebook with the model *code*

In [ ]:
df.to_pickle("./dataset.pkl")